### ISSUE TITLE
Wanted to make sure you are aware of tracespace/gerber-parser

### ISSUE THREAD

**Issue by kasbah** [seveibar/gerbis#2]
Hey, gerbis looks interesting. I wanted to make sure you know about this library: https://github.com/tracespace/tracespace/tree/main/packages/gerber-parser . Just in case it's helpful. No worries if not of course :)

**Comment by seveibar** [comment]
Hey awesome to see you! I was looking at tracespace earlier, it looks like you've done extensive work and testing!

I'm building a new type of open-source EDA software and I wanted to make sure I had a lot of control over the Gerber parsing/serialization process (and a good understanding of it), but duplicating efforts is of course wasteful!

One of the key constraints I'm trying to design around is I'll need to do realtime changes to renderings of the PCB, and have very fast rendering. Gerber is annoying in some sense because the boolean operations from dark/clear mode seem to make it difficult to effectively cache images.

I looked through your profile and saw that you're working on kitspace as well, I was planning on monetizing at the point of assembly/parts ordering as well so it seems you are many steps ahead of me!

I'd love to chat more if you time!

**Comment by kasbah** [comment]
It all sounds very interesting, happy to discuss. I did create Kitspace, and continue to work on it, but I wouldn't say we are ahead in monetizing since it doesn't make money beyond [a little sponsorship](https://opencollective.com/kitspace). :smile: 

Tracespace is mostly the work of Mike Cousins, I have only contributed here and there but we do use it for Kitspace extensively. 

Here are two more links for you:

- https://github.com/kitspace/electro-grammar - parser for electronic component descriptions, also uses Nearley
- https://github.com/monostable/replicad - my sketch of a Typescript DSL for designing circuits (doesn't do much beyond the simple example)

Maybe a good frame for our discussion could be standardization. I have an ongoing project to work on a standard in this area: https://iop.link/ec. I'll send you a DM on Twitter to arrange a meeting. I'll close this issue since it's not really an issue but happy to keep discussing on here as well.

**Comment by seveibar** [comment]
@kasbah we completely independently came up w/ the same idea w.r.t. replicad! I haven't released my builder yet, but here's a sample of the syntax:

![image](https://user-images.githubusercontent.com/1910070/187476832-7f5303da-7656-4d3a-b847-c817e4481863.png)

![image](https://user-images.githubusercontent.com/1910070/187477090-b7eca14f-eaa8-4b47-9e1d-5e1f2e64d6bc.png)

This is all just to build up to a JSX-based multi-output (i.e. gerbers, schematics, 3d) platform, ideally where circuit modules can be shared like react components. Looking forward to the chat!
